stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载 murphysec
    - wget https://github.com/murphysecurity/murphysec/releases/download/v3.0.1/murphysec-linux-amd64
    - docker build -t "$DOCKER_USERNAME"/murphysec:v3.0.1 .
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_USERNAME"/murphysec:v3.0.1
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
#  rules:
#    - if: $CI_COMMIT_TAG
