stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载 murphysec
    - VERSION=v3.1.0
    - wget https://github.com/murphysecurity/murphysec/releases/download/$VERSION/murphysec-linux-amd64
    - docker build -t "$DOCKER_USERNAME"/murphysec:$VERSION-maven-3.6.3-openjdk-17 .
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_USERNAME"/murphysec:$VERSION-maven-3.6.3-openjdk-17
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
#  rules:
#    - if: $CI_COMMIT_TAG
